graph LR
  %% Client
  subgraph Client
    ClientApp[Client App]
  end

    ClientApp --> APIGateway[API Gateway]
    APIGateway --> ConfigServer[Config Server]
    APIGateway --> Discovery[Service Discovery]

    APIGateway --> Search[Search Service]
    APIGateway --> Flight[Flight Service]
    APIGateway --> Pricing[Pricing Service]
    APIGateway --> Inventory[Inventory Service]
    APIGateway --> Reservation[Reservation Service]
    APIGateway --> Payment[Payment Service]
    APIGateway --> CheckIn[Check-in Service]
    APIGateway --> Boarding[Boarding Service]
    APIGateway --> Seating[Seating Service]
    APIGateway --> Baggage[Baggage Service]
    APIGateway --> ClientS[Client Service]
    APIGateway --> Reference[Reference Data Service]
    APIGateway --> Accounting[Accounting Service]
    APIGateway --> DataAnalysis[Data Analysis Service]
    APIGateway --> Notification[Notification Service]

  subgraph Services
    Search
    Flight
    Pricing
    Inventory
    Reservation
    Payment
    CheckIn
    Boarding
    Seating
    Baggage
    ClientS
    Reference
    Accounting
    DataAnalysis
    Notification
  end

  %% Bases de données par service
  subgraph DBs
    DB_Search[(DB Search)]
    DB_Flight[(DB Flight)]
    DB_Pricing[(DB Pricing)]
    DB_Inventory[(DB Inventory)]
    DB_Reservation[(DB Reservation)]
    DB_Payment[(DB Payment)]
    DB_CheckIn[(DB Check-in)]
    DB_Boarding[(DB Boarding)]
    DB_Seating[(DB Seating)]
    DB_Baggage[(DB Baggage)]
    DB_Client[(DB Client)]
    DB_Reference[(DB Reference)]
    DB_Accounting[(DB Accounting)]
    DB_DataAnalysis[(DB DataAnalysis)]
  end

  %% Connexions DB
  Search      --> DB_Search
  Flight      --> DB_Flight
  Pricing     --> DB_Pricing
  Inventory   --> DB_Inventory
  Reservation --> DB_Reservation
  Payment     --> DB_Payment
  CheckIn     --> DB_CheckIn
  Boarding    --> DB_Boarding
  Seating     --> DB_Seating
  Baggage     --> DB_Baggage
  ClientS  --> DB_Client
  Reference   --> DB_Reference
  Accounting  --> DB_Accounting
  DataAnalysis--> DB_DataAnalysis
